"use strict";
const $=id=>document.getElementById(id),audio=$('music'),musicButton=$('music-button'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
function syncMusic(){musicButton.textContent=audio.paused?'♫':'Ⅱ';musicButton.setAttribute('aria-label',audio.paused?'Reproducir música':'Pausar música');musicButton.setAttribute('aria-pressed',String(!audio.paused))}audio.addEventListener('play',syncMusic);audio.addEventListener('pause',syncMusic);musicButton.onclick=()=>audio.paused?audio.play().catch(syncMusic):audio.pause();
$('open').onclick=()=>{$('open').disabled=true;audio.volume=.6;audio.play().catch(syncMusic);$('cover').classList.add('opening');setTimeout(()=>{$('cover').hidden=true;$('content').hidden=false;musicButton.hidden=false;scrollTo(0,0);document.querySelector('.hero h1').focus({preventScroll:true});if(!reduced.matches&&'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.06});document.querySelectorAll('.reveal').forEach(e=>{e.classList.add('waiting');observer.observe(e)})}},reduced.matches?0:1150)};
const memories=[
['La alegría de vivir','Cada flor me recuerda que siempre hay un motivo para sonreír.','Irene con su ramo de flores y globo de cumpleaños'],
['Amor en cada detalle','Los gestos sencillos se convierten en los recuerdos más grandes.','Irene sosteniendo un ramo de rosas claras'],
['Flores para el alma','Hay regalos que llenan las manos y cariños que llenan la vida.','Irene con flores rojas y amarillas'],
['Un corazón agradecido','Guardo en el corazón todo el amor que la vida me ha regalado.','Irene con una manta bordada y un globo'],
['La dicha de compartir','Los días más bonitos tienen una sonrisa y buena compañía.','Irene y un acompañante sentados bajo un árbol'],
['Caminos compartidos','Qué hermoso es caminar la vida con cariño a nuestro lado.','Irene acompañada en un jardín'],
['Momentos al sol','La felicidad también vive en una tarde, un paseo y un abrazo.','Irene con sombrero y un acompañante en un jardín'],
['Recuerdos que abrazan','Hay instantes que pasan, pero su alegría se queda para siempre.','Irene y un acompañante frente a una casa con jardines'],
['Juntos es más bonito','Mi mayor tesoro son las personas con quienes comparto la vida.','Irene en una fotografía de grupo al aire libre'],
['Y aún queda tanto…','Mi historia continúa, y quiero celebrar este nuevo capítulo contigo.','Irene con un ramo junto a una acompañante']
];let current=0,busy=false;
function paint(el,n){const [title,quote,alt]=memories[n];el.replaceChildren();const chapter=document.createElement('p');chapter.className='chapter';chapter.textContent='MI VIDA EN FLORES';const img=document.createElement('img');img.src=`foto-${String(n+1).padStart(2,'0')}.webp`;img.alt=alt;img.draggable=false;const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=quote;const f=document.createElement('span');f.className='folio';f.textContent=String(n+1).padStart(2,'0')+' · IRENE';el.append(chapter,img,h,p,f)}
function controls(){$('prev').disabled=busy||current===0;$('next').disabled=busy||current===memories.length-1;$('page-status').textContent=`Recuerdo ${current+1} de ${memories.length}`;$('restart').hidden=current!==memories.length-1}
function turn(direction){const destination=current+direction;if(busy||destination<0||destination>=memories.length)return;busy=true;controls();const active=$('page-active'),under=$('page-under');if(direction>0){paint(under,destination);active.classList.add('turning-next')}else{paint(under,current);paint(active,destination);active.classList.add('turning-prev')}setTimeout(()=>{current=destination;paint(active,current);active.classList.remove('turning-next','turning-prev');under.replaceChildren();busy=false;controls();if(current+1<memories.length){const preload=new Image();preload.src=`foto-${String(current+2).padStart(2,'0')}.webp`}},reduced.matches?0:800)}
paint($('page-active'),0);controls();$('next').onclick=()=>turn(1);$('prev').onclick=()=>turn(-1);$('restart').onclick=()=>{if(busy)return;current=0;paint($('page-active'),0);controls();$('album-stage').focus({preventScroll:true})};$('album-stage').addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();turn(e.key==='ArrowRight'?1:-1)}});let start=null;$('album-stage').addEventListener('pointerdown',e=>{if(e.isPrimary)start={x:e.clientX,y:e.clientY}});$('album-stage').addEventListener('pointerup',e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.3)turn(dx<0?1:-1)});$('album-stage').addEventListener('pointercancel',()=>start=null);
const offset=(new Date(2026,9,1).getDay()+6)%7;for(let i=0;i<31+offset;i++){const c=document.createElement('span'),day=i-offset+1;if(day>0){c.textContent=day;if(day===17){c.className='selected';c.innerHTML='<svg class="calendar-flower" viewBox="0 0 100 100" aria-hidden="true"><g fill="#d5b5e4" stroke="#9670ae" stroke-width="1.5"><ellipse cx="50" cy="28" rx="14" ry="24"/><ellipse cx="50" cy="28" rx="14" ry="24" transform="rotate(60 50 50)"/><ellipse cx="50" cy="28" rx="14" ry="24" transform="rotate(120 50 50)"/><ellipse cx="50" cy="28" rx="14" ry="24" transform="rotate(180 50 50)"/><ellipse cx="50" cy="28" rx="14" ry="24" transform="rotate(240 50 50)"/><ellipse cx="50" cy="28" rx="14" ry="24" transform="rotate(300 50 50)"/></g><circle cx="50" cy="50" r="19" fill="#fff1c8" stroke="#b49a61" stroke-width="1.5"/></svg><span class="selected-day">17</span>';c.setAttribute('aria-label','17 de octubre, cumpleaños de Irene')}}$('calendar-days').append(c)}
const target=Date.parse('2026-10-17T15:00:00-04:00');function tick(){const t=Math.max(0,Math.floor((target-Date.now())/1000));[Math.floor(t/86400),Math.floor(t/3600)%24,Math.floor(t/60)%60,t%60].forEach((v,i)=>$(['days','hours','minutes','seconds'][i]).textContent=String(v).padStart(2,'0'));if(!t)$('countdown-note').textContent='¡Llegó el día de celebrar mis 60 años!'}tick();setInterval(tick,1000);
for(let i=0;i<24;i++){const p=document.createElement('i');p.style.cssText=`--x:${(i*37)%100}%;--size:${8+i%5*2}px;--duration:${12+i%7*2}s;--delay:${-i*2.7}s;--drift:${i%2?45:-40}px`;$('petals').append(p)}document.addEventListener('visibilitychange',()=>$('petals').classList.toggle('paused',document.hidden));$('back-top').onclick=()=>scrollTo({top:0,behavior:reduced.matches?'instant':'smooth'});
